server {
    listen {{HTTP_PORT}};
    listen [::]:{{HTTP_PORT}};

    server_name {{SERVER_NAME}} www.{{SERVER_NAME}};

    root {{WEBROOT_BASE}}/html;
    index index.html index.htm;

    if ($http_mac_address) { set $tvipmac M; }
    if (-d "{{WEBROOT_BASE}}/prov.mac/$http_mac_address/") { set $tvipres F$tvipmac; }
    if ($tvipres = FM) { rewrite ^/prov/(.*)$ /prov.mac/$http_mac_address/$1 last; }

    location /prov.mac/ { alias {{WEBROOT_BASE}}/prov.mac/; }
    location /prov/     { alias {{WEBROOT_BASE}}/prov/;    }
}
